CREATE VIEW MOVIE_RATINGS_VIEW AS
SELECT M.MOVIE_ID,
	M.MOVIE_NAME,
	M.RELEASE_DATE,
	M.STATUS,
	(CASE
						WHEN A.ROUND IS NULL THEN 0
						ELSE A.ROUND
		END) AS AVERAGE_RATING
FROM MOVIES M
LEFT JOIN
				(SELECT MOVIE_ID,
						ROUND(AVG(RATING),
										2)
					FROM USER_RATINGS
					WHERE ACTIVE = TRUE
					GROUP BY MOVIE_ID) AS A ON M.MOVIE_ID = A.MOVIE_ID